blocks/talks/urls.py
from django.conf.urls import patterns, url

from blocks.talks import views


urlpatterns = patterns(
    '',

    # VIEWS
    url(r'^my_talks/$', views.my_talks, name='block_my_talks'),
    url(r'^review_talks/$', views.review_talks, name='block_review_talks'),
    url(r'^review_talks/(?P<talkid>\d+)/$', views.talk_review,
        name='block_talk_review'),
    url(r'^talk_info/(?P<talkid>\d+)/$', views.talk_info,
        name='block_talk_info'),
    url(r'^edit_talk/(?P<talkid>\d+)/$', views.submit_talk,
        name='block_edit_talk'),
    url(r'^submit_talk/$', views.submit_talk, name='block_submit_talk'),
    url(r'^talks_summary/$', views.talks_summary, name='block_talks_summary'),
)

pyconference/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls import handler404, handler500
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from pyconference.common import views


urlpatterns = patterns(
    '',
    # Skip the logout-confirmation step
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/'}),
    # Login
    (r'^accounts/', include('allauth.urls')),
    # url(r'^pyconference/', include('pyconference.foo.urls')),
    # APIs
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # User Dashboard
    (r'^dashboard/', include('eventmanager.urls')),
    # Realtime API
    (r'^rtapi/', include('rtapi.urls')),
    # Resolve Conferences url
    url(r'^(?P<url>((\w)+(-(\w)+)*)+)/$', views.show_conference,
        name='show_conference'),
    url(r'^(?P<url>((\w)+(-(\w)+)*)+)/', include('blocks.urls')),
    url(r'^blocksapi/', include('blocks.urls_api')),
    # Home
    url(r'^$', views.home, name='home'),
)

handler404 = "pyconference.common.views.error_404"  # lint:ok
handler500 = "pyconference.common.views.error_404"  # lint:ok

rtapi/urls.py
from django.conf.urls import patterns, url

from rtapi import views


urlpatterns = patterns(
    '',
    # API
    url(r'^send_mail2$', views.send_mail2, name='send_mail2'),
)

blocks/talks/models.py
from django.db import models
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from taggit.managers import TaggableManager

from eventmanager.models import Event
from pyconference import settings


class Talk(models.Model):
    BEGINNER = 'B'
    INTERMEDIATE = 'I'
    ADVANCED = 'A'
    LEVEL_CHOICES = (
        (BEGINNER, _('Beginner')),
        (INTERMEDIATE, _('Intermediate')),
        (ADVANCED, _('Advanced')),
    )

    title = models.CharField(max_length=100, verbose_name=_('Title'))
    summary = models.TextField(verbose_name=_('Summary'))
    speaker = models.ForeignKey(User)
    extra_speakers = models.ManyToManyField(
        User, null=True, blank=True, related_name="speakers_user")
    tags = TaggableManager()
    level = models.CharField(
        verbose_name=_('Level'), max_length=1,
        choices=LEVEL_CHOICES, default=INTERMEDIATE)
    knowledge = models.TextField(
        verbose_name=_('Recommended background/knowledge'), null=True,
        blank=True)
    notes = models.TextField(verbose_name=_('Notes'), null=True, blank=True)

    class Meta:
        unique_together = ('speaker', 'title',)

    def __str__(self):
        return self.title


class TalkEvent(models.Model):
    PROPOSED = 'P'
    NEEDS_REVIEW = 'N'
    ANSWERED = 'W'
    UNDER_REVIEW = 'U'
    STATES = (
        (PROPOSED, _('Proposed')),
        (ANSWERED, _('Answered')),
        (NEEDS_REVIEW, _('Needs Review')),
        (UNDER_REVIEW, _('Under Review')),
    )
    talk = models.ForeignKey(Talk)
    event = models.ForeignKey(Event)
    video_url = models.CharField(max_length=200)
    material = models.FileField(upload_to=settings.MATERIAL_PATH)
    state = models.CharField(
        max_length=1, choices=STATES, default=PROPOSED)
    accepted = models.BooleanField(default=False)

    class Meta:
        unique_together = ('talk', 'event',)


class ReviewMessage(models.Model):
    user = models.ForeignKey(User)
    date = models.DateTimeField()
    body = models.TextField()


class TalkVote(models.Model):
    user = models.ForeignKey(User)
    talk_event = models.ForeignKey(
        TalkEvent, null=True, blank=True, default=None)
    accepted = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'talk_event',)


class TalkReview(models.Model):
    talk_event = models.ForeignKey(TalkEvent, unique=True)
    reviewers = models.ManyToManyField(User)
    messages = models.ManyToManyField(ReviewMessage)
    votes = models.ManyToManyField(TalkVote)


#lint:disable
@receiver(models.signals.post_delete, sender=Event)
def handle_deleted_event(sender, instance, **kwargs):
    if instance:
        talk_review = TalkReview.objects.filter(
            talk_event__event=instance).delete()
        talk_event = TalkEvent.objects.filter(event=instance).delete()
#lint:enable

blocks/talks/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.utils import translation
from django.core.mail import EmailMessage

from pyconference.common.utils import render_response
from eventmanager.forms import TalkForm
from blocks.attendees.models import Profile
from blocks.talks.models import (
    Talk, TalkEvent, TalkReview, ReviewMessage
)
from blocks.views import event_context


@login_required
@event_context
def my_talks(request, url, **kw):
    if not kw["context"]["block_my_talks"]:
        raise Http404
    event = kw["event"]
    context = kw["context"]
    context["conference_active"] = "active"
    talks = TalkEvent.objects.filter(
        talk__speaker=request.user, event=event)
    context["talks"] = talks
    translation.activate(context['language'])
    return render_response(request, 'my_talks.html', context)


@login_required
@event_context
def talk_review(request, url, talkid, **kw):
    if not kw["context"]["block_review_talks"]:
        raise Http404
    event = kw["event"]
    context = kw["context"]
    context["organizers_active"] = "active"
    translation.activate(context['language'])
    talk = TalkEvent.objects.filter(id=talkid, event=event).first()
    if not context["is_organizer"] and talk.talk.speaker != request.user:
        raise Http404
    body = request.POST.get("body", "")
    if (request.method == 'GET' and talk) or body == "":
        context["talkid"] = talk.id
        context["talk"] = talk.talk
        levels = {
            Talk.BEGINNER: 'Beginner',
            Talk.INTERMEDIATE: 'Intermediate',
            Talk.ADVANCED: 'Advanced',
        }
        context["talk_level"] = levels[talk.talk.level]
        review, _ = TalkReview.objects.get_or_create(talk_event=talk)
        messages = review.messages.all().order_by("date")
        context["reviews"] = messages
        votes = review.votes.all()
        accepted_by = [vote.user for vote in votes if vote.accepted]
        rejected_by = [vote.user for vote in votes if not vote.accepted]
        user_votes = set(accepted_by + rejected_by + [talk.talk.speaker])
        pending = set(["%s %s" % (
            message.user.first_name, message.user.last_name)
            for message in messages if message.user not in user_votes])
        context["accepted_by"] = ", ".join(
            ["%s %s" % (user.first_name, user.last_name)
             for user in accepted_by])
        context["rejected_by"] = ", ".join(
            ["%s %s" % (user.first_name, user.last_name)
             for user in rejected_by])
        context["pending"] = ", ".join(pending)
        return render_response(request, 'talk_review.html', context)
    elif request.method == 'POST' and talk:
        user = request.user
        review, _ = TalkReview.objects.get_or_create(talk_event=talk)
        message = ReviewMessage(user=user, date=datetime.datetime.now(),
                                body=body)
        message.save()
        if review and message:
            review.messages.add(message)
            if user not in review.reviewers.all():
                review.reviewers.add(user)
            if talk.talk.speaker == request.user:
                talk.state = TalkEvent.ANSWERED
            else:
                talk.state = TalkEvent.NEEDS_REVIEW
            talk.save()
        if user != talk.talk.speaker:
            subject = "Comment added: [%s]" % talk.talk.title
            body_email = "Check out the comments at: %s" % reverse(
                "block_talk_review", args=[url, talkid])
            email = EmailMessage(subject, body_email, to=[
                talk.talk.speaker.email])
            email.send()
        else:
            review, _ = TalkReview.objects.get_or_create(talk_event=talk)
            messages = review.messages.all().order_by("date")
            filter_reviewers = set(
                [m.user.email for m in messages if m.user != user])
            subject = "Comment added: [%s]" % talk.talk.title
            body_email = "Check out the comments at: %s" % reverse(
                "block_talk_review", args=[url, talkid])
            email = EmailMessage(subject, body_email, to=filter_reviewers)
            email.send()

        return HttpResponseRedirect(reverse("block_talk_review",
                                    args=[url, talkid]))
    else:
        raise Http404


@login_required
@event_context
def review_talks(request, url, **kw):
    if not kw["context"]["block_review_talks"]:
        raise Http404
    event = kw["event"]
    context = kw["context"]
    translation.activate(context['language'])
    if not context["is_organizer"]:
        raise Http404
    context["organizers_active"] = "active"
    if context["publish_talk_results"]:
        context["publish_true"] = "checked"
    else:
        context["publish_false"] = "checked"
    talks_db = TalkEvent.objects.filter(event=event).order_by("talk__title")
    talks = []
    tags = set()
    talks_state_color = {
        "A": "funny-boxes-blue",
        "W": "funny-boxes-blue",
        "R": "funny-boxes-grey",
        "Default": "funny-boxes-red"
    }
    for talk in talks_db:
        tags_names = talk.talk.tags.names()
        review = TalkReview.objects.filter(talk_event=talk).first()
        extra_state = "%s" % str(talk.accepted)
        rejected_by = []
        if review:
            votes = review.votes.all()
            rejected_by = [votea.user for votea in votes if not votea.accepted]
            if review and request.user in review.reviewers.all():
                extra_state += " ME"
        if talk.accepted:
            talk_state = "A"
        elif len(rejected_by) > 0:
            talk_state = "R"
        else:
            talk_state = talk.state
        talks.append({
            "id": talk.id,
            "state": talk.state,
            "compose_state": "%s %s" % (talk.state, extra_state),
            "tags": " ".join(tags_names),
            "title": talk.talk.title,
            "author": "%s %s" % (talk.talk.speaker.first_name,
                                 talk.talk.speaker.last_name),
            "summary": talk.talk.summary,
            "talk_state_color": talks_state_color.get(
                talk_state, talks_state_color["Default"])
        })
        for tag in tags_names:
            tags.add(tag)
    context["talks"] = talks
    context["talks_count"] = len(talks)
    context["tags"] = sorted(tags)
    context["eventid"] = event.id
    context["is_admin"] = request.user in event.admin.all()
    return render_response(request, 'review_talks.html', context)


@login_required
@event_context
def talks_summary(request, url, **kw):
    if not kw["context"]["block_review_talks"]:
        raise Http404
    event = kw["event"]
    context = kw["context"]
    translation.activate(context['language'])
    if request.user not in event.admin.all():
        raise Http404
    context["organizers_active"] = "active"
    talks_db = TalkEvent.objects.filter(event=event).order_by("talk__title")
    talks = []
    for talk in talks_db:
        review = TalkReview.objects.filter(talk_event=talk).first()
        votes = review.votes.all()
        accepted = len([votea.user for votea in votes if votea.accepted])
        rejected = len([votea.user for votea in votes if not votea.accepted])
        talks.append({
            "talkid": talk.id,
            "approved": talk.accepted,
            "accepted": accepted,
            "rejected": rejected,
            "title": talk.talk.title,
            "author": "%s %s" % (talk.talk.speaker.first_name,
                                 talk.talk.speaker.last_name),
        })
    talks.sort(key=lambda x: (-x['accepted'], x['rejected']))
    context["talks"] = talks
    context["eventid"] = event.id
    return render_response(request, 'talks_revision_summary.html', context)


@event_context
def talk_info(request, url, **kw):
    #if not kw["context"]["block_talk_page"]:
        #raise Http404
    context = kw["context"]
    translation.activate(context['language'])
    talkid = int(kw["talkid"])
    context["conference_active"] = "active"
    talk = TalkEvent.objects.filter(id=talkid).first()
    if talk and talk.accepted:
        context["talk"] = talk
        profile = Profile.objects.filter(user=talk.talk.speaker).first()
        context["profile"] = profile
        return render_response(request, 'talk_info.html', context)
    else:
        raise Http404


@login_required
@event_context
def submit_talk(request, url, talkid=None, **kw):
    if not kw["context"]["block_submit_talk"]:
        raise Http404
    context = kw["context"]
    context["conference_active"] = "active"
    translation.activate(context['language'])

    if request.method == 'GET':
        if talkid is not None:
            event = kw["event"]
            talk = TalkEvent.objects.filter(id=talkid, event=event).first()
            form = TalkForm(instance=talk.talk)
        else:
            #form = TalkForm(user=request.user)
            form = TalkForm()
        context['talk_form'] = form
        return render_response(request, 'submit_talk.html', context)
    elif request.method == 'POST':
        event = kw["event"]
        if talkid is not None:
            saved_talk_id = int(talkid)
        else:
            saved_talk_id = request.POST.get('saved_talks', None)
            if saved_talk_id:
                saved_talk_id = int(saved_talk_id)
        if saved_talk_id:
            talkEvent = TalkEvent.objects.filter(
                id=saved_talk_id, event=event).first()
            talk = Talk.objects.get(speaker=request.user,
                                    id=talkEvent.talk.id)
            talk_form = TalkForm(request.POST, instance=talk)
        else:
            talk_form = TalkForm(request.POST)
            talk = talk_form.save(commit=False)
            talk.speaker = request.user

blocks/talks/templates/my_talks.html
{% extends base_template %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load url from future %}

{% block styles %}
{{ block.super }}
<link href="{% static 'conference/fancybox/jquery.fancybox-1.3.4.css' %}" rel="stylesheet">
<link href="{% static 'css/conference/design01/css/isotope.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Begin Content -->
            <div class="col-md-12">
                <div class="heading heading-v1 margin-bottom-40">
                    <h2>{% trans 'Proposed Talks:' %}</h2>
                </div>

                {% for talk in talks %}
                <div class="col-md-6" id="talk{{talk.id}}">
                  {# Check the state of the talk and show the header of the box in a different color  #}
                  {% if talk.state == 'N' %}
                    <div class="panel panel-red">
                      <div class="panel-heading">
                          <h3 class="panel-title"><i class="fa fa-bell"></i> {{talk.talk.title}}</h3>
                  {% else %}
                    <div class="panel panel-blue">
                      <div class="panel-heading">
                          <h3 class="panel-title"><i class="fa fa-check"></i> {{talk.talk.title}}</h3>
                  {% endif %}
                        </div>
                        <div class="panel-body">
                            {% if publish_talk_results %}
                              {% if talk.accepted %}
                                <h4><i class="icon-ok"></i> {% trans 'Status: Accepted' %}</h4>
                              {% else %}
                                <h4><i class="icon-remove"> {% trans 'Status: Rejected' %}</h4>
                                {% endif %}
                            {% else %}
                              <h4>{% trans 'Status: ' %}{{talk.get_state_display}}</h4>
                            {% endif %}
                            <p>{{talk.talk.summary|linebreaks}}</p>
                            <ul class="plan-features" id="extraSpeakers">
                              {% for espeaker in talk.talk.extra_speakers.all %}
                                <li><i class="fa fa-user"></i> {{espeaker.username}}</li>
                              {% endfor %}
                            </ul>
                            <ul class="plan-features">
                              {% if publish_talk_results %}
                                {% if talk.accepted %}
                                  <li><i class="icon-ok"></i> {% trans 'Talk Accepted' %}</li>
                                {% else %}
                                  <li><i class="icon-remove"></i> {% trans 'Talk Rejected' %}</li>
                                  {% endif %}
                              {% else %}
                                {% if talk.state == 'N' %}
                                  <li><a href="{% url 'block_talk_review' url=url talkid=talk.id %}"><i class="icon-pencil"></i> {% trans 'Questions pending for your review...' %}</a></li>
                                  {% endif %}
                              {% endif %}
                            </ul>
                        </div>
                        <div>
                          {% if not publish_talk_results %}
                            <a href="javascript:void(0);" class="btn btn-danger btn-large" onclick="removeTalk('{{talk.id}}');">{% trans 'Remove' %} <i class="icon-remove"></i></a>
                          {% endif %}
                          <a href="{% url 'block_edit_talk' url=url talkid=talk.id %}" class="btn btn-info btn-large">{% trans 'Edit Talk' %} <i class="icon-edit"></i></a>
                          <button onclick="showAddSpeaker({{talk.id}})" class="btn btn-u btn-large"><i class="fa fa-user"></i> {% trans 'Add Speaker' %} <i class="icon-edit"></i></button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
          </div>
            <!-- End Content -->
        </div>
    <!--=== End Content Part ===-->

<div class="body">
    <div id="add-speaker" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">{% trans 'Add Speaker' %}</h4>
              </div>
              <div class="modal-body">
                  <div class="control-group">
                      <label for="userName" class="control-label">{% trans 'Speaker name' %}</label>
                      <div class="controls">
                          <input type="text" id="userName" name="name">
                      </div>
                  </div>
              </div>
              <div class="modal-footer">
                  <button data-dismiss="modal" class="btn btn-default">{% trans 'Cancel' %}</button>
                  <button data-dismiss="modal" id="create-event" onclick="addSpeaker()" class="btn btn-success">{% trans 'OK' %}</button>
              </div>            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</div>
{% endblock %}


{% block scripts %}
{{ block.super }}
<script src="{% static 'js/conference/api_conference.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}"></script>
<script src="{% static 'js/dashboard/lib/bootstrap/modal.js' %}"></script>
<script src="{% static 'js/dashboard/ui-dialogs.js' %}"></script>
<script src="{% static 'js/conference/my_talks.js' %}"></script>
{% endblock scripts %}

blocks/talks/templates/submit_talk.html
{% extends base_template %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load url from future %}

{% block styles %}
{{ block.super }}
<link href="{% static 'css/conference/design01/css/select2.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section class="block-large bg-alt">
  <div class="container">
	  <div class="col-md-12">
	      {% crispy talk_form %}
	  </div>
  </div>
</section>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/conference/api_conference.js' %}"></script>
<script src="{% static 'js/dashboard/lib/select2.js' %}"></script>
<script src="{% static 'js/conference/submit_talk.js' %}"></script>
<script>
$("#id_tags").hide();
</script>

<style>
  .form-control {
    padding: 0px 0px;
  }
<style>
{% endblock scripts %}

blocks/talks/templates/talk_info.html
{% extends "conference/design02/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load url from future %}

{% block content %}
  <section class="block-large bg-alt">
		<div class="container">
			<div class="row">
				<!-- Carousel -->
				<div class="col-md-5">
          {% if talk.video_url %}
            <iframe width="100%" height="500" src="{{talk.video_url}}" frameborder="0" allowfullscreen></iframe>
          {% else %}
            <h1 class="text-center">{% trans 'Not video available yet' %}</h1>
          {% endif %}
				</div>
				<!-- Item Description -->
				<div class="col-md-7">
					<h2>{{talk.talk.title}}</h2>
					<p class="lead"><a href="{{profile.personal_page}}">{{talk.talk.speaker.first_name}} {{talk.talk.speaker.last_name}}</a></p>
					<hr>
					<div class="row-fluid">
						<div class="col-md-7">
							<h3>{% trans 'Synopsis:' %}</h3>
							<p>{{talk.talk.summary}}</p>
						</div><!-- /.span6 -->
						<div class="col-md-5">
							<h3>{% trans 'Topics:' %}</h3>
							<div class="well">
								<ul>
									<li><i class="icon-tag"></i> {{talk.talk.get_level_display}}</li>
                  {% for tag in talk.talk.tags.all %}
									         <li><i class="icon-double-angle-right"></i> {{tag.name}}</li>
                  {% endfor %}
								</ul>
                {% if profile.personal_page %}
								<a href="{{profile.personal_page}}" class="btn btn-block"><i class="icon-external-link"></i> {% trans 'View Speaker Website' %}</a>
                {% endif %}
                {% if talk.material %}
								<a href="#" class="btn btn-block btn-primary"><i class="icon-cloud-download"></i> {% trans 'Download presentation' %}</a>
                {% endif %}
							</div>
						</div><!-- /.span6 -->
					</div><!-- /.row-fluid -->
				</div><!-- /.span6 -->
			</div><!-- /.row -->
		</div><!-- /.container -->
	</section>

  {% if related_talks %}

	<section class="block-small">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4>{% trans 'You might want to check out some other interesting talks' %}</h4>
				</div>
			</div>
		</div>
	</section>

	<section class="block-small bg-alt">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="text-center">{% trans 'Related Talks:' %}</h2>
					<br class="spacer-xlarge">
					<ul class="thumbnails portfolio">
            {% for related in related_talks %}
						<li class="col-md-3 cat-1">
							<div class="thumbnail">
								<a href="{{related.url}}">
									<img src="{{related.snapshot}}" alt="">
								</a>
								<div class="caption">
									<h5>{{related.title}}</h5>
									<p>{{related.description}}</p>
								</div>
							</div>
						</li>
            {% endfor %}
					</ul><!-- /.thumbnails.portfolio -->
				</div><!-- /.span12 -->
			</div><!-- /.row -->
		</div><!-- /.container -->
	</section>

  {% endif %}
{% endblock %}

blocks/talks/templates/talk_review.html
{% extends base_template %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load url from future %}

{% block content %}
<section class="block-large">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <form id="reviewTalk" method="POST"
            enctype="multipart/form-data" action="{% url 'block_talk_review' url=url talkid=talkid %}">
              {% csrf_token %}
          <fieldset>
            <div class="row-fluid">
              <div class="col-md-8">
                <h2>{{talk.title}}</h2>
                <h4>{% trans 'Author: ' %}{{talk.speaker.first_name}} {{talk.speaker.last_name}}</h4>
                <p><b>{% trans 'Summary: ' %}</b></p>
                <p>{{talk.summary}}</p>
                <p><b>{% trans 'Level: ' %}</b></p>
                <p>{{talk_level}}</p>
                {% if talk.knowledge %}
                <p><b>{% trans 'Recommended background/knowledge: ' %}</b></p>
                <p>{{talk.knowledge}}</p>
                {% endif %}
                {% if talk.notes %}
                <p><b>{% trans 'Notes: ' %}</b></p>
                <p>{{talk.notes}}</p>
                {% endif %}
              </div><!-- /.span6 -->
              <div class="col-md-4">
                <h3>Topics:</h3>
                <div class="well">
                  <ul>
                    <li><i class="icon-tag"></i> {{talk.get_level_display}}</li>
                    {% for tag in talk.tags.all %}
                     <li><i class="icon-tag"></i> {{tag.name}}</li>
                    {% endfor %}
                  </ul>
                </div>
              </div><!-- /.span6 -->
            </div><!-- /.row-fluid -->
            <div class="row-fluid">
              <div class="col-md-8">
                {% for review in reviews %}
                  <div class="well">
                    {% if talk.speaker.first_name == review.user.first_name and talk.speaker.last_name == review.user.last_name %}
        						      <h4>{{review.user.first_name}} {{review.user.last_name}}:</h4>
                    {% else %}
                      <h4>{% trans 'Question:' %}</h4>
                    {% endif %}
        						<p>{{review.body}}</p>
        					</div>
                {% endfor %}
                <textarea rows="8" style="width: 100%;" name="body" class="input-transparent span12" id="tasksBody"></textarea>
              </div>
              {% if is_organizer %}
              <div class="col-md-4">
                <h3>Votes:</h3>
                <div class="well">
                  <ul>
                    <li><i class="icon-thumbs-up"></i> {% trans 'Accepted by: ' %}<i id="accepted">{{accepted_by}}</i></li>
                    <li><i class="icon-thumbs-down"></i> {% trans 'Rejected by: ' %}<i id="rejected">{{rejected_by}}</i></li>
                    <li><i class="icon-lightbulb"></i> {% trans 'Pending: ' %}<i id="pending">{{pending}}</i></li>
                  </ul>
                  <p>{% trans 'Votes are visible only for organizers' %}</p>
                  <a href="javascript:void(0);" onclick="voteTalk(1, {{talkid}});" class="btn btn-info"><i class="icon-thumbs-up"></i> {% trans 'Accept' %}</a>
                  <a href="javascript:void(0);" onclick="voteTalk(-1, {{talkid}});" class="btn btn-danger"><i class="icon-thumbs-down"></i> {% trans 'Reject' %}</a>
                </div>
              </div>
              {% endif %}
            </div><!-- /.row-fluid -->
          </fieldset>
          <button id="sendReview" class="btn btn-info"><i class="icon-arrow-right"></i>{% trans 'Send' %}</button>
        </form>
      </div><!-- /.span12 -->
    </div><!-- /.row -->
  </div>
</section>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/conference/api_conference.js' %}"></script>
<script src="{% static 'js/conference/talk_review.js' %}"></script>
{% endblock scripts %}